import type {NextPage} from 'next'
import Head from 'next/head'
import {IndexPageTemplate} from "components/templates";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>éphémère</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <main>
        <IndexPageTemplate/>
      </main>
    </div>
  )
}

export default Home
